// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Software Services / SRE Team",
            "url": "http://www.elisa.fi",
            "email": "devops@elisa.fi"
        },
        "license": {
            "name": "Elisa Proprietary License",
            "url": "http://www.elisa.fi"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/doc": {
            "get": {
                "description": "Get OpenAPI documentation",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/hello": {
            "get": {
                "description": "Get hello message",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "Hello message",
                        "schema": {
                            "$ref": "#/definitions/godemo_api.HelloResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Readiness endpoint",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "description": "ready",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "godemo_api.HelloResponse": {
            "type": "object",
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "hello"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Demo",
	Description:      "Demo service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
