name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/base.yml
    with:
      image-tags: sha-${{ github.event.pull_request.head.sha }}
    secrets:
      gar-json-key: ${{ secrets.GAR_JSON_KEY }}

  automerge:
    needs: [build]
    permissions:
      pull-requests: write
      contents: write
    runs-on: elisa-normal
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' ||
      github.event.pull_request.user.login == 'dops-sre'
    steps:
      - name: Automerge dependabot and repo-updater PR's
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.DOPS_SRE_PAT }}
